consul:
  container_name: consul.server
  command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
  image: consul:latest
  volumes_from:
    - consul_config
    - consul_data
  ports:
    - "8500:8500"

vault:
  container_name: vault.server
  image: vault
  links:
    - consul:consul
  ports:
    - "8200:8200"
  volumes_from:
    - vault_config
    - vault_data
    - vault_logs
  cap_add:
    - IPC_LOCK
  command: server

consul_config:
  image: busybox
  volumes:
    - ./etc/consul/config:/consul/config

consul_data:
  image: busybox
  volumes:
    - ./etc/consul/data:/consul/data

vault_config:
  image: busybox
  volumes:
    - ./etc/vault/config:/vault/config

vault_data:
  image: busybox
  volumes:
    - ./etc/vault/data:/vault/data

vault_logs:
  image: busybox
  volumes:
    - ./etc/vault/logs:/vault/logs
